import type { Metadata } from "next";
import { Funnel_Sans } from "next/font/google";
import "./globals.css";
import Provider from './provide';
import { SideNav } from './_components/nav/side_nav';
import { TopNav } from './_components/nav/top_nav';
import { Player } from './_components/player/player';
import { SakuraAside } from './_components/aside/aside';

const funnelSans = Funnel_Sans({
  variable: "--font-funnel_sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "futaba",
  description: "Generated by create next app",
  icons: {
    icon: "/futaba.ico"
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${funnelSans.variable}`}>
      <body data-futaba--theme="oled">
        <Provider>
          <TopNav />
          <div className="middle">
            <SideNav />
            <main>
              {children}
            </main>
            <SakuraAside />
          </div>
          <Player />
        </Provider>
      </body>
    </html>
  );
}
