import type { Metadata } from "next";
import { Familjen_Grotesk, Funnel_Sans, Gamja_Flower, Hanken_Grotesk, Instrument_Serif, Noto_Sans_JP, Noto_Sans_KR, Space_Grotesk } from "next/font/google";
import "./globals.css";
import Provider from './provide';
import { SideNav } from './_components/nav/side_nav';
import { TopNav } from './_components/nav/top_nav';
import { Player } from './_components/player/player';
import { SakuraAside } from './_components/aside/aside';
import { closestCenter, DndContext, DragEndEvent, PointerSensor, useSensor, useSensors } from '@dnd-kit/core';
import { usePlayer } from './api/player';
import { Draggable } from './_components/drag/drag';
import { useSettings } from './api/settings';
import { Body } from './body';

const funnelSans = Hanken_Grotesk({
  variable: "--font-funnel_sans",
  subsets: ["latin"],
});

const instrument = Instrument_Serif({
  subsets: ["latin"],
  style: ["normal", "italic"],
  weight: "400"
})

const notoSansJP = Noto_Sans_JP({
  subsets: ["latin"]
});

const notoSansKR = Noto_Sans_KR({
  subsets: ["latin"]
});

const gamja = Gamja_Flower({
  weight: "400"
});

export const metadata: Metadata = {
  title: "futaba",
  description: "Generated by create next app",
  icons: {
    icon: "/futaba.ico"
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${funnelSans.variable}`}>
      <Body>
        <TopNav />
        <Draggable>
          <div className="middle">
            <SideNav />
            <main>
              {children}
            </main>
            <SakuraAside />
          </div>
        </Draggable>
        <Player />
      </Body>
    </html>
  );
}
